dist: xenial
language: python
python: "3.7"
git:
  depth: 1 # clone only latest revision of repository
cache:
  - pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  # Should fail, because publications.csv is missing
  - goodtables metadata/datapackage.json # structure and schema validation
  # Should fail, because required field "title" is missing
  - cp metadata/publications_missing_title.csv metadata/publications.csv
  - goodtables metadata/datapackage.json
  # Should fail, because required field "name" is missing
  - cp metadata/publications_missing_name.csv metadata/publications.csv
  - goodtables metadata/datapackage.json
  # Should fail, because some rows have missing values for "name" column
  - cp metadata/publications_original.csv metadata/publications.csv
  - goodtables metadata/datapackage.json
